/* Local Word reports and portable reviews. No external libraries or requests. */
(()=>{'use strict';
const labels={title:['匯出報告與比較檔','Export report and review file'],scope:['匯出範圍','Export scope'],all:['全部問題','All issues'],visible:['目前篩選清單','Current filtered list'],confirmed:['已確認問題','Confirmed issues'],custom:['自行選擇問題','Select issues'],word:['Word 報告 (.docx)','Word report (.docx)'],package:['同事觀看用比較檔 (.plancompare)','Review file for colleagues (.plancompare)'],project:['項目名稱','Project'],client:['客戶名稱','Client'],report_title:['報告名稱','Report title'],prepared_by:['編製人','Prepared by'],received_old:['收到舊版圖紙日期','Old drawing received date'],received_new:['收到新版圖紙日期','New drawing received date'],summary:['圖紙簡單改變描述','Brief description of drawing changes'],language:['Word 報告語言','Word report language'],zh:['中文','Chinese'],en:['英文','English'],bilingual:['中英雙語','Chinese and English'],dates:['收到日期按 PDF Date modified 預填，可修改；只保留日期。','Received dates are prefilled from PDF Date modified and can be edited. Only the date appears in the report.'],emptydate:['原檔修改時間未有保存，PDF 也沒有有效修改日期，請填寫。','Original file modification time was not retained and no valid PDF modification date is available. Please enter a date.'],select:['選擇輸出內容','Choose output'],download:['下載選取內容','Download selected output'],busy:['正在準備檔案…','Preparing files…'],close:['關閉','Close'],count:['已選 {n} 項問題','{n} issues selected'],error:['匯出未完成：','Export failed: '],none:['請選擇至少一項問題及輸出格式。','Select at least one issue and output format.'],share:['將比較檔交給同事，再於「觀看比較檔」頁面載入；保留圖紙、圈選位置及覆核狀態。','Send the review file to colleagues and load it in the review viewer. It includes drawing images, issue locations and review status.'],viewer:['觀看比較檔','Open review viewer'],done:['下載已準備。','Downloads are ready.']};
const el=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e};
let session;
const modelLabels={received_old:['舊模型參考快照日期','Earlier reference snapshot date'],received_new:['新模型參考快照日期','Later reference snapshot date'],summary:['模型差異簡單描述','Brief description of model differences'],dates:['日期是可選的報告資料；請依模型快照記錄填寫及核對。','Dates are optional report details. Enter and verify them against the model snapshot records.'],emptydate:['未提供快照日期，可依來源記錄補充。','Snapshot dates are not provided. You may add them from the source records.'],share:['比較檔保留捕捉的模型平面、元素差異、來源欄位及覆核狀態。','The review file retains captured model plans, element differences, source fields and review status.']};
const nativeLabels={share:['比較檔保留模型來源值及 Revit 原生圖紙圖像。圈注輸出、PDF 及圖像一致性仍待實機核對；觀看頁只載入已匯出的結果。','The review file retains model source values and native Revit sheet images. Annotation output and PDF/image consistency require runtime verification. The viewer only displays exported results.']};
function tr(key){const set=session.nativeModelPlan&&nativeLabels[key]?nativeLabels:session.modelReview&&modelLabels[key]?modelLabels:labels;return(set[key]||[key,key])[session.lang==='en'?1:0]}
function download(blob,name){const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)}
function dateValue(v){return window.PlanCompareWord.dateOnly(v)}
function selected(){const s=session,spec=s.scope.value;let list=spec==='visible'?s.opts.visible():spec==='confirmed'?s.opts.issues.filter(i=>s.opts.state(i)==='confirmed'):s.opts.issues;if(spec==='custom')list=list.filter(i=>s.checked.has(i.id));return list}
function updateCount(){session.counter.textContent=tr('count').replace('{n}',selected().length);session.checks.hidden=session.scope.value!=='custom'}
function field(key,type='text'){const wrap=el('label'),title=el('span',tr(key)),input=el(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.id='report-'+key;input.name=key;input.value=key.startsWith('received_')?dateValue(session.metadata[key]):session.metadata[key]||'';if(type==='textarea')input.rows=3;wrap.append(title,input);session.fields[key]=input;return wrap}
async function imageBytes(issues){const files={},names=new Set(issues.map(i=>i.evidence_image).filter(Boolean));for(const name of ['overlay_preview.png'])if(session.opts.data.assets?.[name]||!session.opts.viewerOnly)names.add(name);await Promise.all([...names].map(async name=>{const url=session.opts.assets[name]||name;const r=await fetch(url);if(!r.ok){if(name==='overlay_preview.png')return;throw Error('Missing evidence image: '+name)}files[name]=new Uint8Array(await r.arrayBuffer())}));return files}
async function submit(){const s=session,list=selected();if(!list.length||!s.word.checked&& !s.pack.checked){s.status.textContent=tr('none');return}s.button.disabled=true;s.status.textContent=tr('busy');try{const metadata={...s.metadata};for(const[k,input]of Object.entries(s.fields))metadata[k]=input.value;const reviews=Object.fromEntries(s.opts.issues.map(i=>[i.id,s.opts.state(i)]));if(s.word.checked){const assets=await imageBytes(list);const report=await window.PlanCompareWord.create(s.opts.data,{issues:list,language:'en',metadata,reviews,assets});download(report.blob,report.filename)}if(s.pack.checked){const match=location.pathname.match(/^\/results\/([0-9a-f]{32})\//);if(!match||s.opts.viewerOnly)throw Error('Portable file export is available in the comparison application.');const token=window.PLANCOMPARE_APP_TOKEN||document.querySelector('meta[name="plancompare-token"]')?.content||'';const r=await fetch('/api/jobs/'+match[1]+'/package',{method:'POST',headers:{'Content-Type':'application/json','X-App-Token':token},body:JSON.stringify({issue_ids:list.map(i=>i.id),reviews,metadata})});const body=await r.json();if(!r.ok)throw Error(body.error||'Review file export failed');const file=await fetch(body.url);if(!file.ok)throw Error('Review file download failed');download(await file.blob(),'Drawing_Review_'+match[1].slice(0,8)+'.plancompare')}s.metadata=metadata;s.opts.data.report_metadata=metadata;s.status.textContent=tr('done')}catch(e){s.status.textContent=tr('error')+e.message}finally{s.button.disabled=false}}
function open(opts){const dialog=document.getElementById('exportDialog'),root=document.getElementById('exportControls');if(!dialog||!root)throw Error('Export dialog is unavailable');const lang=opts.language?.()||window.PCStrings?.getLanguage?.()||'zh';session={opts,lang,nativeModelPlan:opts.data.page_background==='native_revit_sheet',modelReview:opts.data.source_kind==='revit_model'||opts.issues.some(i=>i.source_kind==='revit_model'),metadata:{report_title:opts.data.source_kind==='revit_model'||opts.issues.some(i=>i.source_kind==='revit_model')?'Query of Model Differences':'Query of Drawing Differences',...opts.data.report_metadata},fields:{},checked:new Set(opts.visible().map(i=>i.id))};const s=session;root.replaceChildren();dialog.style.width='730px';dialog.style.maxHeight='92vh';dialog.style.overflow='auto';
if(!document.getElementById('pc-export-style')){const style=el('style');style.id='pc-export-style';style.textContent='#exportControls{display:grid;gap:15px;min-width:0}#exportControls h2{font-size:20px}#exportControls label{display:grid;gap:6px;font-size:13px}#exportControls input,#exportControls select,#exportControls textarea{width:100%;font:inherit;border:1px solid #cad9e8;border-radius:8px;padding:8px;background:#f7fbff}#exportControls .export-fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}#exportControls .export-options{display:flex;gap:18px;flex-wrap:wrap}#exportControls .export-options label,#exportControls .export-checks label{display:flex;align-items:center;gap:8px}#exportControls input[type=checkbox]{width:17px;height:17px;flex:none}#exportControls .export-checks{max-height:170px;overflow:auto;background:#fff8;padding:10px;border-radius:9px}#exportControls .export-checks label{font-size:12px;padding:5px}#exportControls .export-note{font-size:12px;color:#647d95;line-height:1.6}#exportControls .export-actions{display:flex;gap:10px;align-items:center}#exportControls .export-actions span{font-size:12px;overflow-wrap:anywhere}@media(max-width:560px){#exportControls .export-fields{grid-template-columns:1fr}}';document.head.append(style)}
root.append(el('h2',tr('title')));const scopeLabel=el('label',tr('scope'));s.scope=el('select');for(const k of ['all','visible','confirmed','custom']){const o=el('option',tr(k));o.value=k;s.scope.append(o)}scopeLabel.append(s.scope);s.scope.value='visible';root.append(scopeLabel);s.counter=el('p');root.append(s.counter);s.checks=el('div');s.checks.className='export-checks';for(const i of opts.issues){const row=el('label'),check=el('input');check.type='checkbox';check.checked=s.checked.has(i.id);check.addEventListener('change',()=>{check.checked?s.checked.add(i.id):s.checked.delete(i.id);updateCount()});row.append(check,el('span',(i.display_number||i.id)+' · '+(window.PCStrings?.issueText?.(i,'title',lang)||i.title||i.id)));s.checks.append(row)}root.append(s.checks);s.scope.addEventListener('change',updateCount);updateCount();const choices=el('div');choices.className='export-options';for(const[k,prop]of [['word','word'],['package','pack']]){const label=el('label'),check=el('input');check.type='checkbox';check.checked=k==='word';label.append(check,el('span',tr(k)));s[prop]=check;if(k!=='package'||!opts.viewerOnly)choices.append(label)}root.append(choices);
const fields=el('div');fields.className='export-fields';for(const k of ['project','client','report_title','prepared_by'])fields.append(field(k));for(const k of ['received_old','received_new'])fields.append(field(k,'date'));root.append(fields);root.append(el('p',tr('dates')));if(!s.metadata.received_old||!s.metadata.received_new)root.append(el('p',tr('emptydate')));root.append(field('summary','textarea'));const l=el('label',tr('language'));s.reportLanguage=el('select');for(const k of ['zh','en','bilingual']){const o=el('option',tr(k));o.value=k;s.reportLanguage.append(o)}s.reportLanguage.value='en';l.append(s.reportLanguage);if(!opts.viewerOnly){const note=el('p',tr('share'));note.className='export-note';const link=el('a',tr('viewer'));link.href='/viewer/';link.target='_blank';link.rel='noopener';note.append(el('br'),link);root.append(note)}const actions=el('div');actions.className='export-actions';s.button=el('button',tr('download'));s.button.addEventListener('click',submit);const close=el('button',tr('close'));close.addEventListener('click',()=>dialog.close());s.status=el('span');s.status.setAttribute('role','status');actions.append(s.button,close,s.status);root.append(actions);dialog.showModal()}
window.PlanCompareExport={open};
})();
