(function(){
  'use strict';const $=id=>document.getElementById(id),words={
    zh:{readonly:'圖紙與模型變更閱覽',title:'查看圖紙與模型變更',intro:'載入直接從 Revit 匯出，或由 PDF 圖紙對比產生的 .plancompare 文件，查看平面圖、分類清單及前後證據，並選取資料匯出 Word 報告。',dropTitle:'把 .plancompare 文件拖到這裡',dropHint:'使用 Revit 或 PDF 對比匯出的閱覽文件。最大 350 MB。',choose:'選擇閱覽文件',step1:'1 · 載入文件',step1Hint:'開啟已匯出結果的 .plancompare 文件。',step2:'2 · 查看變更',step2Hint:'按類別核對模型前後值及原生 PDF 編號圈註；也可查看 PDF 圖紙對比證據。',step3:'3 · 匯出 Word',step3Hint:'選取項目、填寫報告資料，匯出給客戶。',privacy:'文件只在你的瀏覽器內讀取，此頁不會上載圖紙或模型。此頁只展示已匯出的結果，不執行模型變更判定或 PDF 圖紙對比。覆核狀態及待核對的圖面位置仍需人工確認。',openAnother:'載入另一份文件',loading:'正在本機讀取文件及檢查閱覽內容，請稍候…',invalid:'無法載入文件：',extension:'請選擇 .plancompare 分享閱覽文件。',large:'文件大於 350 MB。',missingTemplate:'找不到閱覽程式；請先執行 build_viewer_v9.py 並透過 HTTP 網址開啟此頁。'},
    en:{readonly:'Drawing and model change viewer',title:'Review drawing and model changes',intro:'Open a .plancompare file exported directly from Revit or produced by a PDF drawing comparison to inspect plans, categorized changes and before / after evidence, then select items for a Word report.',dropTitle:'Drop a .plancompare file here',dropHint:'Use a review file exported from Revit or a PDF comparison. Maximum 350 MB.',choose:'Choose review file',step1:'1 · Open file',step1Hint:'Load a .plancompare file containing exported results.',step2:'2 · Review changes',step2Hint:'Review model before / after values and numbered annotations on the native PDF, or inspect PDF drawing comparison evidence.',step3:'3 · Export Word',step3Hint:'Choose items and enter report details to create a client report.',privacy:'Files are read only in your browser. This page never uploads drawings or models. It displays exported results and does not detect model changes or compare PDF drawings. Review decisions and unverified drawing locations still require human confirmation.',openAnother:'Open another file',loading:'Reading the file locally and checking review contents. Please wait…',invalid:'Unable to open review file: ',extension:'Choose a .plancompare review file.',large:'The file exceeds 350 MB.',missingTemplate:'Viewer assets are missing. Run build_viewer_v9.py and open this page using an HTTP address.'}}
  words.zh.sheet='圖紙';words.en.sheet='Sheet';
  let language='zh',active=null,loading=false,templatePromise=null;
  try{language=localStorage.getItem('plancompare.viewer.language')||'zh';}catch(e){}if(!words[language])language='zh';
  function translate(){document.documentElement.lang=language==='en'?'en':'zh-Hant';document.title='PlanCompare · '+words[language].readonly;$('language').value=language;document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=words[language][e.dataset.i18n]);if(loading)$('busy').textContent=words[language].loading;}
  async function template(){if(!templatePromise)templatePromise=fetch('review_template.html',{cache:'no-cache'}).then(async r=>{if(!r.ok)throw Error(words[language].missingTemplate);const text=await r.text();if(!text.includes('__DATA__'))throw Error(words[language].missingTemplate);return text;}).catch(e=>{templatePromise=null;throw e;});return templatePromise;}
  function retainReviews(values){if(!active?.currentData||!values||typeof values!=='object'||Array.isArray(values))return;const ids=new Set(active.currentData.intelligent_review.issues.map(i=>i.id));for(const[id,status]of Object.entries(values))if(ids.has(id)&&['pending','confirmed','ignored'].includes(status))active.reviews[id]=status;}
  function captureReviews(){try{retainReviews($('viewer').contentWindow.PlanCompareReviewStates?.())}catch(e){}}
  function sheetPicker(){const pages=active?.materialized.pages||[],select=$('sheetSelect');$('sheetControl').classList.toggle('hidden',!pages.length);select.replaceChildren();for(const[at,page]of pages.entries()){const option=document.createElement('option');option.value=String(at);option.textContent=page.sheet_number+' · '+page.sheet_name;select.append(option)}select.value=String(active?.pageIndex||0);select.setAttribute('aria-label',words[language].sheet);}
  function render(source){captureReviews();const page=active.materialized.pages[active.pageIndex],data=page?.data||active.materialized.data;active.currentData={...data,reviews:{...active.reviews},review_statuses:{...active.reviews}};let html=PlanCompareBundle.injectData(source,{...active.currentData,language});for(const name of ['ui_strings.js','zip_store.js','docx_report.js','export_controls.js']){const url=new URL('./'+name,location.href).href;html=html.replaceAll('src="'+name+'"',()=> 'src="'+url+'"').replaceAll('src="/assets/'+name+'"',()=> 'src="'+url+'"').replaceAll('src="assets/'+name+'"',()=> 'src="'+url+'"');}html=html.replaceAll('__APP_TOKEN__','__READONLY_VIEWER__');$('viewer').srcdoc=html;$('viewer').title=page?words[language].sheet+' '+page.sheet_number:words[language].readonly;$('viewer').classList.remove('hidden');$('welcome').classList.add('hidden');$('openAnother').classList.remove('hidden');$('loadedFile').textContent=active.filename;sheetPicker();}
  async function load(file){if(!file||loading)return;$('error').classList.add('hidden');if(!/\.plancompare$/i.test(file.name)){error(words[language].extension);return;}if(file.size>350*1024*1024){error(words[language].large);return;}loading=true;$('busy').textContent=words[language].loading;$('busy').classList.remove('hidden');$('bundleFile').disabled=true;
    try{const source=await template(),review=PlanCompareBundle.load(new Uint8Array(await file.arrayBuffer())),materialized=PlanCompareBundle.materialize(review);const previous=active;active={filename:file.name,materialized,source,pageIndex:0,reviews:{...review.reviews},currentData:null};render(source);if(previous)previous.materialized.dispose();}
    catch(e){error(words[language].invalid+e.message);}
    finally{loading=false;$('busy').classList.add('hidden');$('bundleFile').disabled=false;$('bundleFile').value='';}}
  function error(message){$('error').textContent=message;$('error').classList.remove('hidden');}
  function reset(){if(loading)return;captureReviews();$('viewer').srcdoc='';$('viewer').classList.add('hidden');$('welcome').classList.remove('hidden');$('openAnother').classList.add('hidden');$('loadedFile').textContent='';$('sheetControl').classList.add('hidden');$('sheetSelect').replaceChildren();$('error').classList.add('hidden');if(active)active.materialized.dispose();active=null;}
  $('language').onchange=()=>{language=$('language').value;try{localStorage.setItem('plancompare.viewer.language',language);localStorage.setItem('plancompare-language',language);}catch(e){}translate();if(active)render(active.source);};$('bundleFile').onchange=()=>load($('bundleFile').files[0]);$('openAnother').onclick=reset;
  $('sheetSelect').onchange=()=>{if(!active)return;const index=Number($('sheetSelect').value);if(!Number.isInteger(index)||index<0||index>=active.materialized.pages.length)return;captureReviews();active.pageIndex=index;render(active.source);};
  for(const name of ['dragenter','dragover'])$('drop').addEventListener(name,e=>{e.preventDefault();$('drop').classList.add('active');});for(const name of ['dragleave','drop'])$('drop').addEventListener(name,e=>{e.preventDefault();$('drop').classList.remove('active');});$('drop').addEventListener('drop',e=>{if(e.dataTransfer.files.length!==1){error(words[language].extension);return;}load(e.dataTransfer.files[0]);});
  window.addEventListener('message',e=>{if(e.source!==$('viewer').contentWindow||e.origin!==location.origin)return;if(e.data?.type==='plancompare:open-file')reset();else if(e.data?.type==='plancompare:reviews')retainReviews(e.data.reviews);else if(e.data?.type==='plancompare:language'&&['zh','en'].includes(e.data.language)){language=e.data.language;try{localStorage.setItem('plancompare.viewer.language',language);}catch(err){}translate();sheetPicker();}});window.addEventListener('beforeunload',()=>{if(active)active.materialized.dispose();});translate();
  const modelContext=document.modelContext;if(modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(modelContext.registerTool({name:'get_loaded_review_summary',title:'Read loaded review summary',description:'Read the currently loaded sheet comparison summary. Does not upload files or perform a comparison.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty object.');return active?{loaded:true,filename:active.filename,sheet_number:active.currentData.viewer_sheet_number,page_count:active.materialized.pages.length||1,summary:active.currentData.intelligent_review?.summary,source_labels:active.currentData.source_labels}:{loaded:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch(e){}}
})();
