(function(){
  'use strict';const $=id=>document.getElementById(id),words={
    zh:{readonly:'圖紙變更閱覽',title:'直接查看已完成的圖紙對比',intro:'載入同事提供的對比文件，即可查看平面圖、分類清單及舊／新證據，並選取資料匯出 Word 報告。',dropTitle:'把 .plancompare 文件拖到這裡',dropHint:'使用對比頁匯出的「分享閱覽文件」。最大 350 MB。',choose:'選擇對比文件',step1:'1 · 載入文件',step1Hint:'開啟已完成對比的 .plancompare 文件。',step2:'2 · 查看變更',step2Hint:'按類別查看；點編號圈放大證據。',step3:'3 · 匯出 Word',step3Hint:'選取項目、填寫報告資料，匯出給客戶。',privacy:'文件只在你的瀏覽器內讀取。此頁不會上載圖紙，不需 Ollama，也不提供圖紙對比功能。未識別的候選仍須人工核實。',openAnother:'載入另一份文件',loading:'正在本機讀取文件及驗證圖像，請稍候…',invalid:'無法載入文件：',extension:'請選擇 .plancompare 分享閱覽文件。',large:'文件大於 350 MB。',missingTemplate:'找不到閱覽程式；請先執行 build_viewer_v9.py 並透過 HTTP 網址開啟此頁。'},
    en:{readonly:'Drawing change viewer',title:'Review a completed drawing comparison',intro:'Open the review file shared by your colleague to inspect the plan, categorized changes and before / after evidence, then select items for a Word report.',dropTitle:'Drop a .plancompare file here',dropHint:'Use the "Share review file" exported from the comparison page. Maximum 350 MB.',choose:'Choose review file',step1:'1 · Open file',step1Hint:'Load the .plancompare file containing a completed comparison.',step2:'2 · Review changes',step2Hint:'Browse categories and click a numbered circle to zoom into the evidence.',step3:'3 · Export Word',step3Hint:'Choose items and enter report details to create a client report.',privacy:'Files are read only in your browser and are never uploaded by this page. Ollama is not required. This viewer has no drawing comparison function. Unidentified candidates still require human verification.',openAnother:'Open another file',loading:'Reading the file locally and verifying images. Please wait…',invalid:'Unable to open review file: ',extension:'Choose a .plancompare review file.',large:'The file exceeds 350 MB.',missingTemplate:'Viewer assets are missing. Run build_viewer_v9.py and open this page using an HTTP address.'}}
  let language='zh',active=null,loading=false,templatePromise=null;
  try{language=localStorage.getItem('plancompare.viewer.language')||'zh';}catch(e){}if(!words[language])language='zh';
  function translate(){document.documentElement.lang=language==='en'?'en':'zh-Hant';document.title='PlanCompare · '+words[language].readonly;$('language').value=language;document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=words[language][e.dataset.i18n]);if(loading)$('busy').textContent=words[language].loading;}
  async function template(){if(!templatePromise)templatePromise=fetch('review_template.html',{cache:'no-cache'}).then(async r=>{if(!r.ok)throw Error(words[language].missingTemplate);const text=await r.text();if(!text.includes('__DATA__'))throw Error(words[language].missingTemplate);return text;}).catch(e=>{templatePromise=null;throw e;});return templatePromise;}
  function render(source){let html=PlanCompareBundle.injectData(source,{...active.materialized.data,language});for(const name of ['ui_strings.js','zip_store.js','docx_report.js','export_controls.js']){const url=new URL('./'+name,location.href).href;html=html.replaceAll('src="'+name+'"',()=> 'src="'+url+'"').replaceAll('src="/assets/'+name+'"',()=> 'src="'+url+'"').replaceAll('src="assets/'+name+'"',()=> 'src="'+url+'"');}html=html.replaceAll('__APP_TOKEN__','__READONLY_VIEWER__');$('viewer').srcdoc=html;$('viewer').classList.remove('hidden');$('welcome').classList.add('hidden');$('openAnother').classList.remove('hidden');$('loadedFile').textContent=active.filename;}
  async function load(file){if(!file||loading)return;$('error').classList.add('hidden');if(!/\.plancompare$/i.test(file.name)){error(words[language].extension);return;}if(file.size>350*1024*1024){error(words[language].large);return;}loading=true;$('busy').textContent=words[language].loading;$('busy').classList.remove('hidden');$('bundleFile').disabled=true;
    try{const source=await template(),review=PlanCompareBundle.load(new Uint8Array(await file.arrayBuffer())),materialized=PlanCompareBundle.materialize(review);const previous=active;active={filename:file.name,materialized,source};render(source);if(previous)previous.materialized.dispose();}
    catch(e){error(words[language].invalid+e.message);}
    finally{loading=false;$('busy').classList.add('hidden');$('bundleFile').disabled=false;$('bundleFile').value='';}}
  function error(message){$('error').textContent=message;$('error').classList.remove('hidden');}
  function reset(){if(loading)return;$('viewer').srcdoc='';$('viewer').classList.add('hidden');$('welcome').classList.remove('hidden');$('openAnother').classList.add('hidden');$('loadedFile').textContent='';$('error').classList.add('hidden');if(active)active.materialized.dispose();active=null;}
  $('language').onchange=()=>{language=$('language').value;try{localStorage.setItem('plancompare.viewer.language',language);localStorage.setItem('plancompare-language',language);}catch(e){}translate();if(active)render(active.source);};$('bundleFile').onchange=()=>load($('bundleFile').files[0]);$('openAnother').onclick=reset;
  for(const name of ['dragenter','dragover'])$('drop').addEventListener(name,e=>{e.preventDefault();$('drop').classList.add('active');});for(const name of ['dragleave','drop'])$('drop').addEventListener(name,e=>{e.preventDefault();$('drop').classList.remove('active');});$('drop').addEventListener('drop',e=>{if(e.dataTransfer.files.length!==1){error(words[language].extension);return;}load(e.dataTransfer.files[0]);});
  window.addEventListener('message',e=>{if(e.source!==$('viewer').contentWindow||e.origin!==location.origin)return;if(e.data?.type==='plancompare:open-file')reset();else if(e.data?.type==='plancompare:language'&&['zh','en'].includes(e.data.language)){language=e.data.language;try{localStorage.setItem('plancompare.viewer.language',language);}catch(err){}translate();}});window.addEventListener('beforeunload',()=>{if(active)active.materialized.dispose();});translate();
  const modelContext=document.modelContext;if(modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(modelContext.registerTool({name:'get_loaded_review_summary',title:'Read loaded review summary',description:'Read the currently loaded comparison file summary. Does not upload files or perform a comparison.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty object.');return active?{loaded:true,filename:active.filename,summary:active.materialized.data.intelligent_review?.summary,source_labels:active.materialized.data.source_labels}:{loaded:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch(e){}}
})();
